# Generated by Django 5.0 on 2024-03-21 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennywise', '0006_alter_category_options_alter_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='settle_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_transactions', to='pennywise.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settle_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settle_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
