# Generated by Django 5.0 on 2024-03-21 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennywise', '0008_alter_company_name_company_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='current_installment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='installments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settle_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_transactions', to='pennywise.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settle_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settle_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settle_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='pennywise/files/receipts'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='settle_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settle_user_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
