# Generated by Django 5.0 on 2024-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennywise', '0014_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='replicate',
            field=models.CharField(choices=[('B', 'Bimonthly'), ('O', 'Once'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Yearly')], default='O', max_length=1),
        ),
    ]
