# Generated by Django 5.0 on 2024-03-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennywise', '0007_alter_transaction_settle_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='user_company'),
        ),
    ]
