# Generated by Django 5.0 on 2024-04-05 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennywise', '0009_alter_transaction_current_installment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('month_year', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_balances', to='pennywise.account')),
            ],
        ),
    ]
