# Generated by Django 5.0 on 2024-04-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pennywise', '0012_timer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
