# Generated by Django 5.0 on 2024-02-07 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='active',
            new_name='is_active',
        ),
    ]
