# Generated by Django 5.0 on 2024-03-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennywise', '0003_alter_company_options_alter_company_name_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='settle_receipt',
            field=models.ImageField(null=True, upload_to='pennywise/files/receipts'),
        ),
    ]
