# Generated by Django 5.0 on 2024-03-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pennywise', '0005_rename_has_repeated_transaction_has_replicated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
